### ISSUE TITLE
Warnings into STDOUT instead of STDERR

### ISSUE THREAD

**Issue by marqueda** [DecodeGenetics/svimmer#1]
Dear Hannes,

First of all, thank you for writing and maintaining such great resources as graphtyper and svimmer!

I have noticed that svimmer writes warnings into STDOUT, messing up piping into bgzip / a VCF file if no variant is present for one of the chromosomes in one of the input VCF files. This is only a minor complication as warnings could be grepped out before bgzip.

Nevertheless, it would be nicer to stream into STDERR instead, by adjusting line 77 to:
```print("Warning: Contig '%s' was not found in file %s!" % (chrom, vcf_filename.rstrip("\n")), file=sys.stderr)```

Thanks and best,
David

**Comment by hannespetur** [comment]
Thank you. You are right, the warning should print to STDERR. I will make your suggested change.

Best,
Hannes

**Comment by marqueda** [comment]
Great, thanks for the quick reply / fix!
