### ISSUE TITLE
svimmer

### ISSUE THREAD

**Issue by vitty0513** [DecodeGenetics/svimmer#10]
Dear,
Dose the svimmer generate SVs  that can be detected by all softerwares ( intersection of SVs from different softewares), or merge all SVs of different files (union of SVs from different softewares)? 
Many thanks!

**Comment by hannespetur** [comment]
No, it won't work with VCFs from all softwares. It's designed with Manta input in mind but might work with some others too.

Best, Hannes

**Comment by vitty0513** [comment]
Thanks very much!
How dose it merge similar SVs from multiple VCF files? For example, if there're 3 files, dose it keep SVs that are present in two or three files?

**Comment by zhachengwan** [comment]
I have also encountered the same problem. When the file is 3, merge_SV is greater than 3. Do you know what the underlying principle is? thanks you！！！
