### ISSUE TITLE
join-mode 

### ISSUE THREAD

**Issue by jjfarrell** [DecodeGenetics/svimmer#11]
@hannespetur 

Just a couple questions on join-mode...

What is the difference between the two  join-modes? When should the non-default join-mode be used (eg: join_mode=false)?

Is the output different or is it related to some optimizing of the run-time?

--join-mode",
                        dest="join_mode",
                        action="store_true",
                        help="""Set if the merging should join VCFs from the first file to the other files."""

**Comment by hannespetur** [comment]
Hey. Sorry for the confusion.

There is only one join mode. If `--join_mode=false` then the program will run in default mode (i.e. not use join mode). Join mode has different output. 

default mode is useful for merging discovered SVs in multiple samples. It will output SVs found in all input files and output how many were merged (INFO/NUM_MERGED_SVS). Assuming two input files, A and B, it's the union of A and B.

join mode will print all SVs in A (first file) and print how many SVs from B were merged with it (INFO/NUM_JOINED_SVS). When I've used this method I used a truth VCF as the first file and a query VCF second to measure the sensitivity.  

Best,
Hannes
