### ISSUE TITLE
support SVIM VCF

### ISSUE THREAD

**Issue by biozzq** [DecodeGenetics/svimmer#4]
Hi，

I found the SVTYPE for duplication annotated by three differet types in SVIM VCF: "DUP", "DUP:TANDEM", "DUP:INT". Maybe I need add `info_dict["SVTYPE"] == "DUP:TANDEM" or info_dict["SVTYPE"] == "DUP:INT"` to the following part highlighted by italic. Also, from the following codes, why did you treat the INV as the INS?
Join related SV types
        if "SVTYPE" in info_dict:
            if info_dict["SVTYPE"] == "DEL_ALU" or info_dict["SVTYPE"] == "DEL_LINE1":
                info_dict["SVTYPE"] = "DEL"
            **_elif info_dict["SVTYPE"] == "ALU" or info_dict["SVTYPE"] == "LINE1" or info_dict["SVTYPE"] == "SVA" or \
                 info_dict["SVTYPE"] == "DUP" or info_dict["SVTYPE"] == "CNV" or info_dict["SVTYPE"] == "INVDUP" or \
                 info_dict["SVTYPE"] == "INV":_**
                info_dict["SVTYPE"] = "INS"
            elif info_dict["SVTYPE"] == "TRA":
                info_dict["SVTYPE"] = "BND"

Sincerely,
Zheng Zhuqing

**Comment by hannespetur** [comment]
Hello, yes you can add those two in there to merge/join. I had to consider INV as insertions is because I was joining my SV calls with a truth set that reported them as insertions.

Best,
Hannes
